In [1]:
import numpy as np
import pandas as pd

In [2]:
#list를 받아 ndarray 생성 => array() : ndarray생성하는 함수
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [3]:
a=[1,2,3]
a

[1, 2, 3]

In [4]:
# shape : attribute
# array1 : object(ndarray)
array1.shape
#3행으로 들어갔다.
#[1,
# 2,
# 3.]

(3,)

In [5]:
type(array1)

numpy.ndarray

In [6]:
arr1 = np.array([
    [1],
    [2],
    [3]
])
arr1.shape

(3, 1)

In [7]:
# 2차원 행렬 생성 : ndarray 생성
arr2 =np.array([
    [1,2,3],
    [4,5,6]
])
arr2.shape

(2, 3)

In [8]:
array3 = np.array([
    [1,2,3]
])
array3.shape

(1, 3)

# numpy.attr
- shape : row x col
- ndim : n-dimension

In [9]:

str_='array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'
print(str_.format(array1.ndim, arr2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [10]:
list =[1,2,3]

In [11]:
type(list)

list

In [12]:
array1= np.array(list)

In [13]:
#dtype => attribute =>get,set
array1.dtype

dtype('int32')

In [14]:
#dtype을 16으로 낮췄더니 0들이 추가됨
array1

array([1, 2, 3])

In [15]:
list2 = [1,2,'test']
arr2 =np.array(list2)
print(arr2)
print(arr2.dtype)

['1' '2' 'test']
<U11


In [16]:
list3 = [1,2,3.0]
arr3 = np.array(list3)
print(arr3,arr3.dtype)

[1. 2. 3.] float64


In [17]:
#강제 형변환 =>astype('변환할 데이터 타입')<=메소드
arr_int = np.array([1,2,3])
arr_int.dtype

dtype('int32')

In [18]:
arr_float=arr_int.astype('float64')
arr_float.dtype

dtype('float64')

In [19]:
arr_float1 = np.array([1.1,2.1,3.1])
arr_float1.dtype

dtype('float64')

In [20]:
arr_int2 = arr_float1.astype('int32')
print(arr_int2.dtype)
print(arr_int2)

int32
[1 2 3]


In [21]:
import numpy as np

In [22]:
seq_arr = np.arange(10) #10 : stop value, start value : 0, step : 1
print(seq_arr)
print(seq_arr.dtype, seq_arr.shape)


[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [23]:
seq_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
zero_arr = np.zeros((3,2), dtype='int16')
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape)

[[0 0]
 [0 0]
 [0 0]]
int16 (3, 2)


In [25]:
one_arr = np.ones((3,2))#ones의 default = float
print(one_arr)
print(one_arr.dtype,one_arr.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [26]:
arr1 = np.arange(10)
print('arr1 : ',arr1)

arr1 :  [0 1 2 3 4 5 6 7 8 9]


In [27]:
print('hi','hi')
print('hi'+'hi')

hi hi
hihi


In [28]:
arr2 = arr1.reshape(2,-1)
print('arr2 : \n',arr2)

arr2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
arr3 = arr1.reshape(-1,2)
print('arr3 : \n',arr3)

arr3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [30]:
arr3.reshape(-1,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# tolist() method => ndarray =>
arr1 = np.arange(8)
print(arr1)

[0 1 2 3 4 5 6 7]


In [32]:
arr3d = arr1.reshape((2,2,2))
print(arr3d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [33]:
arr3d.tolist()# 복사해서 처리한 것, 원본 :arr3d는 변환이 없음=> ndarray

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

In [34]:
arr5= arr3d.reshape(-1,1)

In [35]:
arr5

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [36]:
arr5.tolist()

[[0], [1], [2], [3], [4], [5], [6], [7]]

In [37]:
arr5# 1차원 배열 : arr1
arr1.reshape(-1,1) # 8 x 1 형태

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [38]:
arr1.reshape(-1,1).shape

(8, 1)

In [39]:
arr1d = np.arange(1,10)
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [41]:
arr1d[arr1d>5] #[] : indexing

array([6, 7, 8, 9])

In [42]:
#행렬(Matrix)정렬
org_arr = np.array([3,1,9,5])
org_arr

array([3, 1, 9, 5])

In [43]:
sort_arr1 = np.sort(org_arr)
sort_arr1

array([1, 3, 5, 9])

In [44]:
org_arr

array([3, 1, 9, 5])

In [45]:
sort_arr2 = org_arr.sort() #원본이 정렬된다. return값 없음 sort_arr2에는 None이 들어간다.
sort_arr2

In [46]:
org_arr

array([1, 3, 5, 9])

In [47]:
sort_arr1[::-1]

array([9, 5, 3, 1])

In [48]:
sort_array1_desc = np.sort(org_arr)[::-1]
sort_array1_desc

array([9, 5, 3, 1])

In [49]:
# 2차원 정렬 : 축(axis)지정
arr2d = np.array([
    [1,2],
    [2,1]
])

In [50]:
sort_arr2d = np.sort(arr2d)
sort_arr2d

array([[1, 2],
       [1, 2]])

In [51]:
sort_arr2d = np.sort(arr2d, axis=0)
sort_arr2d
# [1, 1],
# [2, 2]]

array([[1, 1],
       [2, 2]])

In [52]:
sort_arr2d = np.sort(arr2d, axis=1)
sort_arr2d

array([[1, 2],
       [1, 2]])

In [53]:
#정렬된 인덱스만 반환 =>np.argsort()
org_arr = np.array([3,1,9,5])
org_arr

array([3, 1, 9, 5])

In [54]:
np.sort(org_arr) #원본은 유지된 상황, 정렬된 결과가 반환된다.

array([1, 3, 5, 9])

In [55]:
indexes = np.argsort(org_arr)
#정렬을 하는 것이 아닌 정렬된 인덱스만 반환함.

In [56]:
org_arr[indexes] # org_arr[[1,0,3,2]]
#fancy색인에는 list,ndarray가 들어갈 수 있다.
#iterator,map,filter,zip 외우기

array([1, 3, 5, 9])

In [57]:
x=np.array([1,2,3])
y=np.array(['h','a','p'])

In [58]:
arrays = np.array([[a,b] for a,b in zip(x,y)])

In [59]:
list = [[a,b] for a,b in zip(x,y)]

In [60]:
type(list)

list

In [61]:
name_arr = np.array(['홍길동','고길동','마이콜','희동이','듈리'])

In [62]:
score_arr = np.array([78,95,84,98,88])

In [63]:
# 성적을 정렬 => 인덱스 값을 추출
index_ = np.argsort(score_arr)

In [64]:
index_

array([0, 2, 4, 1, 3], dtype=int64)

In [65]:
name_arr[index_][::-1]

array(['희동이', '고길동', '듈리', '마이콜', '홍길동'], dtype='<U3')

In [66]:
name_arr[index_[::-1]]

array(['희동이', '고길동', '듈리', '마이콜', '홍길동'], dtype='<U3')

In [67]:
a=[1,2,3,4,5]

In [68]:
a[::-1]

[5, 4, 3, 2, 1]

In [69]:
#전치행렬(2차원) : 대문자로 기재
A = np.array([
    [1,2],
    [3,4]
])

In [70]:
A

array([[1, 2],
       [3, 4]])

In [71]:
t_A = np.transpose(A)
t_A

array([[1, 3],
       [2, 4]])

### pandas
- 엑셀의 표와 같다
- 데이터타입 : Series, DataFrame
    - Series : Column
    - DataFrame : Series를 여러개 모아 놓는것

In [72]:
import pandas as pd
import numpy as np

In [73]:
# train.csv 파일 읽어서 DataFrame 생성
titanic_df = pd.read_csv('./data/train.csv')

In [74]:
# DataFrame 확인
# method : head(개수), tail(개수)

## DataFrame의 구조 => row index, column index, value

In [75]:
titanic_df.head(3) # 개수 지정 x  =>5개나옴

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [76]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [77]:
type(titanic_df)

pandas.core.frame.DataFrame

In [78]:
#values(ndarray) 값을 가져온다.
titanic_df.shape

(891, 12)

In [79]:
#RangeIndex(class)=>row index 
#object라고 나오는 datatype => 문자열이다. dataframe이 추정해서 문자열 만들어줌.
# 해당 DataFrame 구조 확인 method =>info()
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [80]:
#DataFrame 기초 통계 확인 메소드 : describe()
#describe()를 통해 리턴되는 표는 dataframe이다. 이걸 사용 할 수 있음.
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [81]:
value_counts = titanic_df['Pclass']
type(value_counts)

pandas.core.series.Series

In [82]:
value_counts

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [83]:
# value_counts는 Series의 메소드이다. 
value_counts = titanic_df['Pclass'].value_counts()

In [84]:
value_counts

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [85]:
#리스트를 사용해서 데이터프레임 생성 코드

col_name1 = ['col1'] # 컬럼명
list1 =[1,2,3] # value에 사용할 데이터
arr1 = np.array(list1) #ndarray : value에 사용할 데이터
df_list1 = pd.DataFrame(
    list1 # value에 사용할 리스트 지정
    ,columns=col_name1# 컬럼명에 사용할 리스트 지정
)
df_list1

col1
0     1
1     2
2     3

In [86]:
df_arr1 = pd.DataFrame(
    arr1
    ,columns = col_name1
)
df_arr1

col1
0     1
1     2
2     3

In [87]:
#컬럼이 3개인 데이터 프레임 생성

In [88]:
col_name2=['이름','국어','영어'] # 컬럼명에 사용할 리스트

# value에 들어갈 리스트 생성 : 2차원
list2 =[
     ['홍길동',100,100]
    ,['고길동',90,90]
]
df_list2 = pd.DataFrame(
    list2
    ,columns = col_name2
)

df_list2


이름   국어   영어
0  홍길동  100  100
1  고길동   90   90

In [89]:
arr2 = np.array(list2)#ndarray 생성
arr2

array([['홍길동', '100', '100'],
       ['고길동', '90', '90']], dtype='<U11')

In [90]:
df_arr2= pd.DataFrame(
    arr2
    ,columns=col_name2
)
df_arr2

이름   국어   영어
0  홍길동  100  100
1  고길동   90   90

In [91]:
df_arr2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      2 non-null      object
 1   국어      2 non-null      object
 2   영어      2 non-null      object
dtypes: object(3)
memory usage: 176.0+ bytes


In [92]:
# 데이터프레임 생성 : 딕셔너리 사용
# Series는 key value로 구성(dict)
# key = column 명, value = value
dict_ ={
     '이름' : ['홍길동','고길동']
    ,'국어' : [100,100]
    ,'영어' : [90,90]
}

dict_

{'이름': ['홍길동', '고길동'], '국어': [100, 100], '영어': [90, 90]}

In [93]:
df_dict = pd.DataFrame(dict_)
df_dict

이름   국어  영어
0  홍길동  100  90
1  고길동  100  90

In [94]:
arr3 = df_dict.values
arr3

array([['홍길동', 100, 90],
       ['고길동', 100, 90]], dtype=object)

In [95]:
list3 = df_dict.values.tolist()
list3

[['홍길동', 100, 90], ['고길동', 100, 90]]

In [96]:
#DataFrame => Dict 꺼낸다.
dict3 = df_dict.to_dict('list')
dict3

{'이름': ['홍길동', '고길동'], '국어': [100, 100], '영어': [90, 90]}

In [97]:
titanic_df.columns.to_list()

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [98]:
df_dict

이름   국어  영어
0  홍길동  100  90
1  고길동  100  90

In [99]:
df_dict.columns = ['name','kor','eng']

In [100]:
df_dict

name  kor  eng
0  홍길동  100   90
1  고길동  100   90

In [101]:
titanic_df['Age_0'] = 0 #Age_0 컬럼을 추가하고 0으로 초기화

In [102]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0  
3      0            113803  53.1000  C123        S      0  
4      0            373450   8.0500   NaN        S      0

In [103]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Age_0'],
      dtype='object')

In [104]:
test_arr = np.arange(3)
test_arr

array([0, 1, 2])

In [105]:
#루프 없이 반복되는 브로드캐스팅
test_arr = test_arr+1
test_arr

array([1, 2, 3])

In [106]:
# 나이의 모든 값에 10을 곱하자 => 새로운 컬럼을 생성하자.
titanic_df['Age_by_10'] = titanic_df['Age']*10
# 리턴해야할 컬럼이 한개면 Series, 2개 이상이면 DataFrame

titanic_df[['Age_by_10', 'Age']].head(3) #fancy 색인

Age_by_10   Age
0      220.0  22.0
1      380.0  38.0
2      260.0  26.0

In [107]:
# 타이타닉에서 가족수를 구해서 컬럼을 생성
# SibSp 컬럼 : 배우자나 형제
# Parch 컬럼 : 부모나 자식
titanic_df['Family_No'] = titanic_df['SibSp']+ \
titanic_df['Parch']+1
titanic_df['Family_No']

0      2
1      2
2      1
3      2
4      1
      ..
886    1
887    1
888    4
889    1
890    1
Name: Family_No, Length: 891, dtype: int64

In [108]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Age_0', 'Age_by_10',
       'Family_No'],
      dtype='object')

In [109]:
#Age_0컬럼 삭제 : drop(), axis=1
titanic_drop_df = titanic_df.drop("Age_0", axis=1, inplace=False)#labels가 첫번째 파라미터라서 명시 안해도 labels="Age_0"이 된다.
titanic_drop_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Age_by_10',
       'Family_No'],
      dtype='object')

In [110]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Age_0', 'Age_by_10',
       'Family_No'],
      dtype='object')

In [111]:
#원본에 있는 Age_0 컬럼을 삭제 : 원본삭제 => inplace =True
titanic_df.drop(labels="Age_0", axis=1, inplace=True)
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Age_by_10',
       'Family_No'],
      dtype='object')

In [112]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Age_by_10',
       'Family_No'],
      dtype='object')

In [113]:
#여러개 컬럼을 삭제, 원본 삭제
titanic_df.drop(    
    labels=['Age_by_10','Family_No'] #여러개 컬럼 지정
    ,axis=1 #컬럼 선택
    ,inplace = True #원본에 반영하겠다. True이면 return이 없다.=>대입된게 없다. print 하면 None 나옴
)

In [114]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [115]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [116]:
# Row Drop : Index 사용해서 삭제
titanic_df.drop(
    labels = [0,1,2]# 삭제할 Row 선택
    , axis = 0 # 삭제할 축 기정
    , inplace = True # 원본 반영 여부
)

In [117]:
titanic_df.head(3) # named index라서 0,1,2가 아닌 3,4,5부터 뜬다.

PassengerId  Survived  Pclass  \
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   
5                              Moran, Mr. James    male   NaN      0      0   

   Ticket     Fare Cabin Embarked  
3  113803  53.1000  C123        S  
4  373450   8.0500   NaN        S  
5  330877   8.4583   NaN        Q

In [118]:
# 타이타닉 데이터 다시 로딩
titanic_df = pd.read_csv('./data/train.csv')

In [119]:
indexes = titanic_df.index

In [120]:
#index 변수에는 row index(rangeIndex)만 나온다. index=>Row
print(indexes)

RangeIndex(start=0, stop=891, step=1)


In [121]:
#인덱스의 값 추출(ndarray로 되어있음... numpy임.. 루프없이 반복, 팬시,불리언 색인 가능. map,zip,enumerate 처리 가능.)
indexes.values #ndarray : 인덱싱,슬라이싱,팬시색인,불린색인 가능

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [122]:
indexes.shape

(891,)

In [123]:
type(indexes.values)

numpy.ndarray

In [124]:
indexes[0] #인덱싱 : 단일값 추출

0

In [125]:
indexes[:6].values # slicing 1 - indexes 가지고 나와서 value를 추출한 경우.

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [126]:
indexes.values[:6]# slicing 2 - 891개 가지고 나와서 그중에 6개만 가지고옴.

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [127]:
# 아주 주의: index value는 변경 불가
# indexes[0]=5

In [128]:
series_fair = titanic_df['Fare']

In [129]:
type(series_fair)

pandas.core.series.Series

In [130]:
series_fair.max()#numpy 메소드

512.3292

In [131]:
series_fair.sum()#numpy 메소드

28693.9493

In [132]:
#내장함수
sum(series_fair)

28693.949299999967

In [133]:
#결과가 ndarray라 head가능
(series_fair+3).head(3)

0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

In [134]:
series_fair.head(3)

0     7.2500
1    71.2833
2     7.9250
Name: Fare, dtype: float64

In [135]:
#reset_index를 쓰게되면 index가 컬럼으로 빠져나온다.
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass  \
0      0            1         0       3   
1      1            2         1       1   
2      2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [136]:
#reset_index() 활용 예제
value_cnts = titanic_df['Pclass'].value_counts()
# index의 값 1 =>1등칸, 2=>2등칸, 3=>3등칸... 이걸 컬럼으로 빼야한다.
value_cnts

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [137]:
new_value_cnts =value_cnts.reset_index(inplace=False)
#컬럼이 두개네!=>DataFrame으로 바뀐다, 컬럼이 하나면 Series
#drop=True로 설정하면 기존 컬럼(index column)삭제
new_value_cnts

index  Pclass
0      3     491
1      1     216
2      2     184

In [138]:
# (:)사용 => row selection
titanic_df[0:2]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [139]:
#[컬럼명 사용] => column selection
titanic_df['Pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [140]:
titanic_df[0:2]['Pclass'] #row를 가져오는것

0    3
1    1
Name: Pclass, dtype: int64

In [141]:
titanic_df['Pclass'][0:2] #column을 가져오는 것.

0    3
1    1
Name: Pclass, dtype: int64

In [142]:
#대괄호안에 연산자가 들어가면 row selection이다. 결국 pclass가 3인것을 고르라는 코드이다.
# DataFrame return
titanic_df[titanic_df['Pclass']==3].head(3)
#우리 모두 콜론(:)을 연산자로 봅시다.

PassengerId  Survived  Pclass                      Name     Sex   Age  \
0            1         0       3   Braund, Mr. Owen Harris    male  22.0   
2            3         1       3    Heikkinen, Miss. Laina  female  26.0   
4            5         0       3  Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket   Fare Cabin Embarked  
0      1      0         A/5 21171  7.250   NaN        S  
2      0      0  STON/O2. 3101282  7.925   NaN        S  
4      0      0            373450  8.050   NaN        S

In [144]:
# titanic_df.ix[0,2] # ix[row,column]

In [145]:
data ={
     'Name':['C','E','J','S']
    ,'Year':[2011,2016,2015,2015]
    ,'Gender':['M','F','M','M']
}
data

{'Name': ['C', 'E', 'J', 'S'],
 'Year': [2011, 2016, 2015, 2015],
 'Gender': ['M', 'F', 'M', 'M']}

In [146]:
data_df = pd.DataFrame(
    data
    , index =['one','two','three','four']
)
data_df

Name  Year Gender
one      C  2011      M
two      E  2016      F
three    J  2015      M
four     S  2015      M

In [148]:
# data_df.ix

In [149]:
#data_df.ix[  0,    0]
#           row,column
#data_df.ix['one',0]

In [150]:
# data_df.iloc[0,'Name'] --error

In [151]:
#data_df.iloc['one',0] #Named Index Error

In [152]:
data_df

Name  Year Gender
one      C  2011      M
two      E  2016      F
three    J  2015      M
four     S  2015      M

In [153]:
data_df_reset = data_df.reset_index()

In [154]:
data_df_reset

index Name  Year Gender
0    one    C  2011      M
1    two    E  2016      F
2  three    J  2015      M
3   four    S  2015      M

In [155]:
#컬럼명 변경
#columns ={'변경할 컬럼명':변경될 컬럼명}
data_df_reset= data_df_reset.rename(
    columns={'index':'old_index'}
)

In [156]:
data_df_reset.loc[1,'Name']

'E'

In [157]:
data_df_reset.index.values

array([0, 1, 2, 3], dtype=int64)

In [158]:
(data_df_reset.index+1).values

array([1, 2, 3, 4], dtype=int64)

In [159]:
#row range index의 값을 실제적으로 1개씩 더함
data_df_reset.index = data_df_reset.index+1

In [160]:
data_df_reset

old_index Name  Year Gender
1       one    C  2011      M
2       two    E  2016      F
3     three    J  2015      M
4      four    S  2015      M

In [161]:
data_df_reset.loc[1,'Name']

'C'

In [162]:
data_df

Name  Year Gender
one      C  2011      M
two      E  2016      F
three    J  2015      M
four     S  2015      M

In [163]:
#문자 start : end-1 근데 'two'는 문자열이기 때문에 -1이 되지 않는다. 그렇기에 start:end가 된다. end값이 제외되지 않는다.
# dataframe에서는 -indexing이 없다.
data_df.loc['one':'two','Name']

one    C
two    E
Name: Name, dtype: object

In [164]:
data_df.iloc[0:1,0] #end값이 제외되었다. integer index로 접근.

one    C
Name: Name, dtype: object

In [165]:
data_df.loc['one','Name']

'C'

In [166]:
data_df_reset.index = data_df_reset.index+1

In [167]:
#named기반일때는 end값이 제외가 되지 않는다.
data_df_reset.iloc[0:2,1]

2    C
3    E
Name: Name, dtype: object

In [170]:
#loc[] : Named index를 사용한다.
#iloc[] : Integer index를 사용한다. => position index를 사용한다.

In [171]:
# 불린 인덱싱
titanic_df = pd.read_csv('./data/train.csv')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [172]:
#불리언 인덱싱으로 row를 정하고, fancy색인으로 컬럼 정하기
titanic_df[titanic_df['Age']>60 ][['Name','Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [173]:
#df.loc[row,column]을 통해 row에 boolean, column엔 fancy
titanic_df.loc[titanic_df['Age']>60,['Name','Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [174]:
# 나이 >60, 선실등급 : 1, 성별 : 여자 승객만 추출
# 모든컬럼이라 loc[row,column]에서 column은 빠져도 된다.
titanic_df.loc[(titanic_df['Age']>60) &(titanic_df['Pclass']==1)&(titanic_df['Sex']=='male')]

PassengerId  Survived  Pclass                                  Name  \
54            55         0       1        Ostby, Mr. Engelhart Cornelius   
96            97         0       1             Goldschmidt, Mr. George B   
170          171         0       1             Van der hoef, Mr. Wyckoff   
252          253         0       1             Stead, Mr. William Thomas   
438          439         0       1                     Fortune, Mr. Mark   
456          457         0       1             Millet, Mr. Francis Davis   
493          494         0       1               Artagaveytia, Mr. Ramon   
545          546         0       1          Nicholson, Mr. Arthur Ernest   
555          556         0       1                    Wright, Mr. George   
625          626         0       1                 Sutton, Mr. Frederick   
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
745          746         0       1          Crosby, Capt. Edward Gifford   

      Sex   Age  SibSp  Parch     Ticket      Fare        Cabin Embarked  
54   male  65.0      0      1     113509   61.9792          B30        C  
96   male  71.0      0      0   PC 17754   34.6542           A5        C  
170  male  61.0      0      0     111240   33.5000          B19        S  
252  male  62.0      0      0     113514   26.5500          C87        S  
438  male  64.0      1      4      19950  263.0000  C23 C25 C27        S  
456  male  65.0      0      0      13509   26.5500          E38        S  
493  male  71.0      0      0   PC 17609   49.5042          NaN        C  
545  male  64.0      0      0        693   26.0000          NaN        S  
555  male  62.0      0      0     113807   26.5500          NaN        S  
625  male  61.0      0      0      36963   32.3208          D50        S  
630  male  80.0      0      0      27042   30.0000          A23        S  
745  male  70.0      1      1  WE/P 5735   71.0000          B22        S

In [175]:
cond1=(titanic_df['Age']>60) 
cond2=(titanic_df['Pclass']==1)
cond3=(titanic_df['Sex']=='female')
titanic_df[cond1&cond2&cond3]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

In [178]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

PassengerId  Survived  Pclass                              Name     Sex  \
845          846         0       3               Abbing, Mr. Anthony    male   
746          747         0       3       Abbott, Mr. Rossmore Edward    male   
279          280         1       3  Abbott, Mrs. Stanton (Rosa Hunt)  female   

      Age  SibSp  Parch     Ticket   Fare Cabin Embarked  
845  42.0      0      0  C.A. 5547   7.55   NaN        S  
746  16.0      1      1  C.A. 2673  20.25   NaN        S  
279  35.0      1      1  C.A. 2673  20.25   NaN        S

In [181]:
titanic_sorted = titanic_df.sort_values(by=['Pclass','Name'], ascending=[True,False])
titanic_sorted

PassengerId  Survived  Pclass                                    Name  \
325          326         1       1                Young, Miss. Marie Grice   
555          556         0       1                      Wright, Mr. George   
55            56         1       1                       Woolner, Mr. Hugh   
351          352         0       1  Williams-Lambert, Mr. Fletcher Fellows   
155          156         0       1             Williams, Mr. Charles Duane   
..           ...       ...     ...                                     ...   
401          402         0       3                         Adams, Mr. John   
365          366         0       3          Adahl, Mr. Mauritz Nils Martin   
279          280         1       3        Abbott, Mrs. Stanton (Rosa Hunt)   
746          747         0       3             Abbott, Mr. Rossmore Edward   
845          846         0       3                     Abbing, Mr. Anthony   

        Sex   Age  SibSp  Parch     Ticket      Fare Cabin Embarked  
325  female  36.0      0      0   PC 17760  135.6333   C32        C  
555    male  62.0      0      0     113807   26.5500   NaN        S  
55     male   NaN      0      0      19947   35.5000   C52        S  
351    male   NaN      0      0     113510   35.0000  C128        S  
155    male  51.0      0      1   PC 17597   61.3792   NaN        C  
..      ...   ...    ...    ...        ...       ...   ...      ...  
401    male  26.0      0      0     341826    8.0500   NaN        S  
365    male  30.0      0      0     C 7076    7.2500   NaN        S  
279  female  35.0      1      1  C.A. 2673   20.2500   NaN        S  
746    male  16.0      1      1  C.A. 2673   20.2500   NaN        S  
845    male  42.0      0      0  C.A. 5547    7.5500   NaN        S  

[891 rows x 12 columns]

In [182]:
#Cabin has about 700 NaN
#Age has about 200 NaN
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [183]:
#Fancy Indexing
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [185]:
#팬시색인으로 이중리스트를 쓰면 dataframe으로 나온다.
type(titanic_df[['Fare']])
#대괄호 한개만 쓰면 Series가 나온다.
type(titanic_df['Fare'])

pandas.core.series.Series

In [186]:
# Aggregation function 메소드의 리턴은 Series가 된다. Age, Fare가 컬럼이 아닌 Row인덱스가 된다.

type(titanic_df[['Age','Fare']].mean())

pandas.core.series.Series

In [189]:
type(titanic_df.groupby('Pclass')[['PassengerId','Survived']].count())

pandas.core.frame.DataFrame

In [191]:
titanic_df.groupby('Pclass')['Age'].agg([max,min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [192]:
titanic_df['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ... 
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [193]:
#fillna()는 원본 바꾸지 않는게 default
titanic_df['Cabin'].fillna('C000')

0      C000
1       C85
2      C000
3      C123
4      C000
       ... 
886    C000
887     B42
888    C000
889    C148
890    C000
Name: Cabin, Length: 891, dtype: object

In [194]:
titanic_df['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ... 
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [200]:
#?치면 메소드의 구조가 나온다.
titanic_df.fillna?

In [ ]:
titanic_df['Cabin'].fillna

In [201]:
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')

In [202]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500  C000        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250  C000        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500  C000        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000  C000        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500  C000        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500  C000        Q  

[891 rows x 12 columns]

In [204]:
titanic_df['Cabin'].fillna('C000', inplace=True)

In [205]:
titanic_df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [207]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin            0
Embarked         2
dtype: int64